### ISSUE TITLE
ValueError: Unsupported block size with this feature axis

### ISSUE THREAD

**Issue by yiwusuorao** [SEAL-UCSB/block_compression#2]
I got the question as follows:
@F0815-s07:~/block_compression-master/speedup$ python mm_profile.py
2018-10-29 05:25:25.464176: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-10-29 05:25:28.874199: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties:
name: Tesla P100-PCIE-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285
pciBusID: 0000:2d:00.0
totalMemory: 15.89GiB freeMemory: 15.60GiB
2018-10-29 05:25:29.123536: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 1 with properties:
name: Tesla P100-PCIE-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285
pciBusID: 0000:31:00.0
totalMemory: 15.89GiB freeMemory: 15.60GiB
2018-10-29 05:25:29.383380: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 2 with properties:
name: Tesla P100-PCIE-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285
pciBusID: 0000:35:00.0
totalMemory: 15.89GiB freeMemory: 15.60GiB
2018-10-29 05:25:29.662219: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 3 with properties:
name: Tesla P100-PCIE-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285
pciBusID: 0000:39:00.0
totalMemory: 15.89GiB freeMemory: 15.60GiB
2018-10-29 05:25:29.673039: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Device peer to peer matrix
2018-10-29 05:25:29.673146: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1051] DMA: 0 1 2 3
2018-10-29 05:25:29.673159: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1061] 0:   Y Y Y Y
2018-10-29 05:25:29.673167: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1061] 1:   Y Y Y Y
2018-10-29 05:25:29.673174: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1061] 2:   Y Y Y Y
2018-10-29 05:25:29.673181: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1061] 3:   Y Y Y Y
2018-10-29 05:25:29.673203: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:2d:00.0, compute capability: 6.0)
2018-10-29 05:25:29.673213: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:1) -> (device: 1, name: Tesla P100-PCIE-16GB, pci bus id: 0000:31:00.0, compute capability: 6.0)
2018-10-29 05:25:29.673222: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:2) -> (device: 2, name: Tesla P100-PCIE-16GB, pci bus id: 0000:35:00.0, compute capability: 6.0)
2018-10-29 05:25:29.673230: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:3) -> (device: 3, name: Tesla P100-PCIE-16GB, pci bus id: 0000:39:00.0, compute capability: 6.0)
Traceback (most recent call last):
  File "mm_profile.py", line 61, in <module>
    actual_sparsity, execution_time = profile(batch_size=256, input_size=4096, output_size=4096, block_size=block_size, sparsity=sparsity)
  File "mm_profile.py", line 32, in profile
    bsmm = BlocksparseMatMul(layout, block_size=block_size)
  File "/home/s00420976/.local/lib/python3.5/site-packages/blocksparse/matmul.py", line 59, in __init__
    raise ValueError("Unsupported block size with this feature axis")
ValueError: Unsupported block size with this feature axis

My experience environment’s configured as follows.
Ubuntu 16.04+cuda 8.0+cudnn 6.0+python 3.5+tensorflow 1.11.0(GPU nvidia P100 )
I don's any idea about this question.Thank in advance.

**Comment by ji-u** [comment]
This error is raised from the blocksparse library. 
They only support 8, 16, and 32 block sizes for block-sparse matrix multiplication.
Could you check which block size is used when the Error raised?

**Comment by ji-u** [comment]
I just checked the blocksparse library.
They have updated their code recently and change the constraints.
They only support 8, 16, and 32 in the first axis, and only support 32 in the second axis.
In my code, I test 8x8, 16x16, and 32x32. You could change it to 8x32, 16x32, and 32x32 to make the code work in the current blocksparse library.

**Comment by yiwusuorao** [comment]
you are right!I modify the code as fellows:
with open('mm_execution_time.csv', 'w') as f:
    f.write('block_size, sparsity, exeuction_time\n')
    block_size = 32
    #for block_size in (8, 16, 32):
    for sparsity in (0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9):
        actual_sparsity, execution_time = profile(batch_size=256, input_size=4096, output_size=4096, block_size=block_size, sparsity=sparsity)
        print('%d, %f, %d' % (block_size, actual_sparsity, execution_time))
        f.write('%d, %f, %d\n' % (block_size, actual_sparsity, execution_time))
the question is sovled! Thank a lot
